- scanners/boostsecurityio/trivy-fs/module.yaml
- scanners/boostsecurityio/trivy-image/module.yaml
- scanners/boostsecurityio/trivy-sbom-image/module.yaml
- scanners/boostsecurityio/trivy-sbom/module.yaml
Tested using smoke tests here
https://github.com/boost-sandbox/trivy-testing/actions/runs/5259865014/workflow
Last successful run here comparing existing Prod vs this feature branch
https://github.com/boost-sandbox/trivy-testing/actions/runs/5259865014
> Update Trivy to 0.42.1

- scanners/boostsecurityio/native-scanner/rules.yaml
Adding to default for now until the ci/cd rules are moved out of default/native.
> default: add github rules

- rules-realm/boostsecurityio/sca-cve/rules.yaml
We will update all existing SCA scanners to use this rules realm to avoid copy pasting everytime.
> BST-5714 - Create rules realm for SCA modules with CVEs

- rules-realm/boostsecurityio/stored-secrets/rules.yaml
This will be used by both flavors of gitleaks
> BST-5714 - Add rules realm for secrets scanners

- scanners/boostsecurityio/codeql/module.yaml
Tested using module smoke tests comparing prod and dev
https://github.com/boost-sandbox/module-tests-codeql/actions/runs/5291133699
> CodeQL - Remove CWE allow list and update version to 2.13.4

- .github/workflows/registry-scanner.yaml
- scanners/examples/example-diff-sarif/module.yaml
- scanners/examples/example-main-sarif/module.yaml
This version brings validation for the scan_types.
> BST-6121: Updated scanner-registry-action to v1.4

- scanners/boostsecurityio/scanner/module.yaml
- Fix FP in cicd-unpinned-dependencies
> Update BoostSecurity Scanner

- server-side-scanners/boostsecurityio/sca/module.yaml
- server-side-scanners/boostsecurityio/sca/rules.yaml
Add server side scanner SCA for SBOM definition
> [BST-6132] add SBOM sca scanner

- .github/workflows/registry-scanner.yaml
https://github.com/boostsecurityio/scanner-registry-action/releases/tag/v1.5.2
> Updated registry action to v1.5.2

- server-side-scanners/boostsecurityio/checkmarx-provider/rules.yaml
the group best-practices doesn;t exist.
> checkmarx rules db, change group best-practices to top-10-design-patterns.

- server-side-scanners/boostsecurityio/checkmarx-provider/rules.yaml
there;s a bunch of categories not supported, are being removed.
> Fix checkmarx db

- server-side-scanners/boostsecurityio/checkmarx-provider/rules.yaml
more categories needed to be removed.
> checkmarx rules db fixes

- scanners/boostsecurityio/semgrep/module.yaml
Reverts boostsecurityio/dev-registry#78
> Revert "Revert boostsecurityio/semgrep"

- server-side-scanners/boostsecurityio/cicd/rules.yaml
- cicd-scm-limit-repo-creation
- cicd-scm-org-verified
> BST-7786-Add-new-CICD-rules

- server-side-scanners/boostsecurityio/oss-license/module.yaml
- server-side-scanners/boostsecurityio/oss-license/rules.yaml
Description & ref url are placeholder for now
> BST-6647: new server-side scanner Boost OSS license

- scanners/boostsecurityio/semgrep-pro/module.yaml
- scanners/boostsecurityio/semgrep/module.yaml
Adds vulnerability_ids in SAST results properties
> update semgrep post-processors

- scanners/boostsecurityio/osv-scanner/module.yaml
Latest upgrade of osv. Has been smoke tested and latest converter confirmed to have fixed a bug in previous version.
> BST-10572 OSV Scanner Upgrade

- scanners/boostsecurityio/osv-scanner/module.yaml
Smoke tested: https://github.com/boost-sandbox/module-tests-osv/actions/runs/9210753217
> Latest OSV Scanner 

- scanners/boostsecurityio/checkov-tf-plan/module.yaml
- scanners/boostsecurityio/checkov-tf-plan/rules.yaml
- scanners/boostsecurityio/checkov/module.yaml
- scanners/boostsecurityio/checkov/rules.yaml
- update checkov to 3.2.108
- add 121 rules 
- pyyaml seems to have decided to remove the quotes from pretty_names so the diff is bigger than it really is
> update checkov 3.2.108

- scanners/boostsecurityio/osv-scanner/module.yaml
The new converter version supports reachability.
> [BST-11135] Upgrade converter for OSV scanner

- scanners/boostsecurityio/trivy-fs/module.yaml
- scanners/boostsecurityio/trivy-image/module.yaml
> BST-11485 Latest Trivy Scanners

- server-side-scanners/boostsecurityio/sci-sca/rules.yaml
import the sca-cve rules in the sci-sca module
> BST-11539: add sci sca rules

- server-side-scanners/boostsecurityio/sci-sca/rules.yaml
Re apply #140 
> import the sca-cve rules in the sci-sca module
> BST-11539 Add sci sca rules

- scanners/boostsecurityio/modelscan/module.yaml
- scanners/boostsecurityio/modelscan/rules.yaml
Smoke tested here https://github.com/boost-sandbox/module-tests-modelscan/actions/runs/10149190724/job/28063563401
> BST-11654 - Modelscan

- scanners/boostsecurityio/supply-chain-inventory/module.yaml
> BST-11844 BST-11782 Update SCI Version

- scanners/boostsecurityio/composition/module.yaml
- scanners/boostsecurityio/supply-chain-inventory/module.yaml
More AI rules added to cover more libraries
Smoke tested https://github.com/boost-sandbox/module-tests-supply-chain-inventory/actions/runs/10251590141/job/28359974417#step:3:43
> BST-11652 - Update composition scanner

- server-side-scanners/boostsecurityio/sci-sca/rules.yaml
a new rule is added for  SCA from SCI scanner,
> [BST-12208] Adds AI load unsafe model for SCA from SCI

- rules-realm/boostsecurityio/stored-secrets/rules.yaml
Create rule for each original rule ID.
Script to generate this is in the ticket.
> [BST-12096] Create new secrets rule database

- rules-realm/boostsecurityio/stored-secrets/rules.yaml
Fixes the pretty name, the description for the secrets rules.
> [BST-12254] Curating the secrets rules database for gitleaks

- scanners/boostsecurityio/checkov-tf-plan/module.yaml
- scanners/boostsecurityio/checkov/module.yaml
- scanners/boostsecurityio/gitleaks-full/module.yaml
- scanners/boostsecurityio/gitleaks/module.yaml
* BST-12075 Latest Checkov Processor (#158)
* BST-12323: rename gitleaks validate secret env var (#169)
* BST-12576 Fix Checkov Parsing (#171)
---------
> Synch Fork 

- scanners/boostsecurityio/composition/module.yaml
Update to latest version  https://github.com/boostsecurityio/boostsec-scanner-composition/pull/30
Smoke tests for the module ran successfully against this dev registry PR:
https://github.com/boost-sandbox/module-tests-composition/actions/runs/11015399389/job/30588378431
> BST-12455 Latest Composition Scanner

- scanners/boostsecurityio/composition/module.yaml
This updates composition scanner to PII detection
> BST-12455 Latest Composition Scanner (Adding PII)

- scanners/boostsecurityio/trivy-fs/module.yaml
- scanners/boostsecurityio/trivy-image/module.yaml
- scanners/boostsecurityio/trivy-sbom-image/module.yaml
- scanners/boostsecurityio/trivy-sbom/module.yaml
latest trivy with fix for golang purls in sbom.
Smoke tests: https://github.com/boost-sandbox/module-tests-trivy/actions/runs/11857856758
> Latest Trivy with Fix for Purls

- .github/workflows/registry-scanner.yaml
Adds support for remediation on rules
> Update registry-scanner.yaml to use v1.5.7 of scanner-registry-action

- scanners/boostsecurityio/baseline/module.yaml
This change is to update the boost scanner version
> [BST-14049] update scanner native version

- scanners/boostsecurityio/supply-chain-inventory/module.yaml
Adds much more inventory detections
> BST-14092 Latest SCI

- scanners/boostsecurityio/osv-scanner/module.yaml
smoke tested: https://github.com/boost-sandbox/module-tests-osv/actions/runs/14447158808
> BST-14847 Osv Scanner V2

- scanners/boostsecurityio/osv-scanner/module.yaml
Smoke tests : https://github.com/boost-sandbox/module-tests-osv/actions/runs/14802281379
> Updated the include files to comply with OSV scanner version

- scanners/boostsecurityio/gitleaks-full/module.yaml
- scanners/boostsecurityio/gitleaks/boost.toml
- scanners/boostsecurityio/gitleaks/module.yaml
Smoke tests : https://github.com/boost-sandbox/module-tests-gitleaks/actions/runs/15004944167/job/42161086830
> Added support for Boost Gitleaks rules customization

- scanners/boostsecurityio/baseline/module.yaml
> Update native / baseline to remove old CID rule
