scanners/boostsecurityio/brakeman/module.yaml

Last successful smoke tests run  (with Docker manifest digest)
https://github.com/boost-sandbox/module-tests-brakeman/actions/runs/5262289129
With configuration against this feature branch
https://github.com/boost-sandbox/module-tests-brakeman/actions/runs/5262289129/workflow
Previous version vs latest outputs almost the same findings on the target projects, except that it gives 2 more findings for `railsgoat`, otherwise the same as before. For `postal` project it gives 2 more as CWE-1104 (unmaintained gems)

BST-5714 - Update brakeman to v6.0.1

---

scanners/boostsecurityio/gosec/module.yaml

Updated from 2.14.0 to 2.16.0
https://github.com/securego/gosec/compare/v2.14.0...v2.16.0
---
Latest smoke tests run here
https://github.com/boost-sandbox/module-tests-gosec/actions/runs/5268108474
Using this feature branch
https://github.com/boost-sandbox/module-tests-gosec/actions/runs/5268108474/workflow
---
Results are very similar but it appears that on some target projects it produces a few less findings (ex. `osv-scanner` project gives 19 instead of 23 and `gitleaks` has 10 instead of 11)
Looks like those missing are all because of `G307` which indeed was literally omitted https://github.com/securego/gosec/commit/d5a9c737234eaf1ac0ac26fc299c6a5f5212730e , we will keep the stale rule in the `rules.yaml` as we never know if they bring it back....

BST-5714  - Update gosec to 2.16.0

---

scanners/boostsecurityio/snyk-test/module.yaml

Based on latest metadata file
https://static.snyk.io/cli/v1.1179.0/release.json
Last succesful run
https://github.com/boost-sandbox/module-tests-snyk/actions/runs/5270282526
Against this feature branch
https://github.com/boost-sandbox/module-tests-snyk/actions/runs/5270282526/workflow
---
Returns no more, no less than before, but it's finding a lot less than Trivy does ... :(
---
Before
After

BST-5714 - Update Snyk to latest 1.1179.0

---

.github/workflows/registry-scanner.yaml

Updated scanner-registry-action to [v1.2.0](https://github.com/boostsecurityio/scanner-registry-action/releases/tag/v1.2.0).
This version allows for automatic update detection for scanner imports.
Testing was done in [my fork](https://github.com/ledo01/dev-registry), where I created a dummy scanner and rules-realm before updating the action version.
I then updated only the rule-realm and made sure that an upload was triggered for the dummy scanner, also confirmed that the data was correct in the rules-management backend.

BST-5993: Updated registry-action to v1.2.0

---

.github/workflows/registry-scanner.yaml

Because we expect to receive PRs from forks (including our own `dev-registry`), we need to use `pull_request_target` because we need to use the `vars` (not necessarily the `secrets`) during the PR validation stage.
This is considered safe because the repo does not contain any execution content, the only action we run is maintained entirely by us and designed to consume untrusted data (`rules.yaml` and `module.yaml` in a way that is safe)

Fix GHA workflow for PRs from forks

---

.github/workflows/registry-scanner.yaml

Reverse sync from Prod to Dev (sorry -- this is because we wanted to get the `pull_request_target` on the upstream first)
* Update registry action to v2.0 and use pull_request_target

Update registry action to v1.2.0 and use pull_request_target (#32)

---

.github/workflows/registry-scanner.yaml

In the PR context, we don't really need the real docs var. We can use the default one, as we do not do 404 checks on it anyway

Do not use pull_request_target (#36)

---

scanners/boostsecurityio/semgrep/module.yaml

Depends on https://github.com/boostsecurityio/boostsec-scanner-semgrep/pull/16
Please approve that one first ^, so that we can pin the hash on the `main` branch there.
Tested using module tests
https://github.com/boost-sandbox/module-tests-semgrep/actions/runs/5291114081
`main` branch converter
https://app.circleci.com/pipelines/github/boostsecurityio/boostsec-scanner-semgrep/79/workflows/08786201-aceb-49ac-988c-b2523f382634/jobs/165?invite=true#step-116-7

BST-5714 - Remove semgrep CWE allow list

---

.github/workflows/registry-scanner.yaml

Added `reopened` event for PR to ease this kind re-trigger in the future
We were missing step security action in community org and blocked the registry scan

Add ability to re-trigger workflow

---

.github/workflows/registry-scanner.yaml

Updated scanner-registry-action to version v1.3. This version enabled the use of server-side scanners (ex: CI/CD, Dependabot, ...).
This new version was tested in my [personal fork](https://github.com/ledo01/dev-registry/pull/5), where I updated to the lasted version then, added a server-side scanner, making sure it was parsed and uploaded correctly.

BST-6077: scanner-registry-action v1.3

---

server-side-scanners/boostsecurityio/cicd/module.yaml
server-side-scanners/boostsecurityio/cicd/rules.yaml

Created a new module for CICD using the newly added "server-side" feature. The rules were imported from the native-scanner that are currently used in scm-integrations with some extra that were added recently (0584a8a)

BST-6116: CICD server-side module

---

.github/workflows/registry-scanner.yaml
server-side-scanners/boostsecurityio/cicd/module.yaml
server-side-scanners/boostsecurityio/dependabot/module.yaml

Scan types for server-side scanners are defined in the backend, having
them in the module file is not needed.

BST-5970: Remove scan-types for server-side scanners

---

scanners/boostsecurityio/osv-scanner/module.yaml

- Updating to latest version of OSV 1.3.5
- Fixed converter bug (see https://github.com/boostsecurityio/boostsec-converter-sca/pull/20)
- Added MacOS x64 support
-----
Updated hashes for 1.3.5
```
VERSION=1.3.5; for ARCH in MACOS_X86_64=darwin_amd64 MACOS_ARM64=darwin_arm64 LINUX_X86_64=linux_amd64 LINUX_ARM64=linux_arm64; do KEY=${ARCH%%=*}; VALUE=${ARCH#*=}; echo "${KEY}_SHA: $(curl -sSL https://github.com/google/osv-scanner/releases/download/v${VERSION}/osv-scanner_${VERSION}_${VALUE} | sha256sum | cut -d' ' -f1)"; done
```

BST-6033 - Fix OSV support

---

scanners/boostsecurityio/scanner/module.yaml

Recently performed an upgrade to the scanner-native repository to use an image backed by Wolfi. The change in this repository is to adopt the change from the scanner-native repository.

BST-4915: Updating boostsecurityio scanner to latest scanner-native

---

scanners/boostsecurityio/scanner/module.yaml

Not exploitable, but still patching for CVE hygiene

Update BoostSecurity scanner for OpenSSL CVEs

---

server-side-scanners/boostsecurityio/blackduck/module.yaml
server-side-scanners/boostsecurityio/blackduck/rules.yaml

Added BlackDuck as a server-side scanner using the sca-cwe rules.

BST-7278: add blackduck server-side module

---

scanners/boostsecurityio/semgrep-pro/README.md
scanners/boostsecurityio/semgrep-pro/module.yaml
scanners/boostsecurityio/semgrep-pro/rules.yaml
scanners/boostsecurityio/semgrep/module.yaml

- Declares semgrep-pro module
- Updated semgrep at the same time
- Installs semgrep pro, requires new mandatory API token parameter (`SEMGREP_APP_TOKEN`)
- Ran smoke tests https://github.com/boost-sandbox/module-tests-semgrep/actions/runs/6163218790/job/16726307889
Uses manifest digest for latest multi-arch semgrep Docker image
```
docker buildx imagetools inspect returntocorp/semgrep:1.39.0 | head -n3
Name:      docker.io/returntocorp/semgrep:1.39.0
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:fd3d6ccd390677db83880d99a9f494500c003ec82177cc141f6ec37f71633a96
```

BST-7524 Add semgrep pro

---

scanners/boostsecurityio/semgrep-pro/module.yaml
scanners/boostsecurityio/semgrep/module.yaml

While working on semgrep pro module, discovered that existing semgrep module did not correctly support mono repo slices
Some months ago some modules (checkov and brakeman) had been updated https://github.com/boost-community/scanner-registry/commit/f7460e2e51a21d59b162b78e9d68faae72e95976 but not semgrep
Smoke tested
https://github.com/boost-sandbox/module-tests-semgrep/actions/runs/6177943657/job/16770151890

BST-7784 - Fix modules to properly support monorepo

---

scanners/boostsecurityio/checkov-tf-plan/rules.yaml
scanners/boostsecurityio/checkov/rules.yaml

This was done back when the original rule ID was hidden from the user and is now redundant.

checkov: Remove rule prefix from pretty name

---

scanners/boostsecurityio/bearer-pii/module.yaml
scanners/boostsecurityio/bearer/module.yaml
scanners/boostsecurityio/brakeman/module.yaml
scanners/boostsecurityio/codeql/module.yaml
scanners/boostsecurityio/gitleaks-full/module.yaml
scanners/boostsecurityio/gitleaks/module.yaml
scanners/boostsecurityio/gosec/module.yaml

- Follow up of https://github.com/boostsecurityio/dev-registry/pull/88 for gosec, codeql, brakeman, bearer and gitleaks.

Update SAST scanners

---

scanners/boostsecurityio/trivy-image/module.yaml

This update is to handle missing `Metadata.RepoTags` from the trivy output (ref: https://github.com/boostsecurityio/boostsec-scanner-trivy/pull/23)

Updated trivy-image post-processor

---

server-side-scanners/boostsecurityio/cicd/rules.yaml

Making a pass to make a `supply-chain-cicd-severe-issues` the Elevated GitHub App rule. Especially since now, we are allow listing our own app, we should show that other apps ask for more permissions.

Make Elevated GitHub App rule a Severe Supply Chain finding

---

server-side-scanners/boostsecurityio/cicd/module.yaml
server-side-scanners/boostsecurityio/dependabot/module.yaml
server-side-scanners/boostsecurityio/oss-license/module.yaml
server-side-scanners/boostsecurityio/sbom-sca/module.yaml
server-side-scanners/boostsecurityio/snyk-provider/module.yaml
server-side-scanners/boostsecurityio/sonarqube/module.yaml

drive-by: fix invalid `scan-types` key for several scanners.

BST-9547: change boost sbom oss scanner to license

---

scanners/boostsecurityio/codeql/module.yaml
scanners/boostsecurityio/semgrep-pro/module.yaml
scanners/boostsecurityio/semgrep/module.yaml

For codeql, semgrep and semgrep pro, add a setup step where we output the config used based on the environment variables.
Note that the output will only be visible if you run the CLI in `TRACE` mode.

[BST-9435] add script to output public config

---

server-side-scanners/boostsecurityio/sbom-sca/rules.yaml

Depends-on: https://github.com/boostsecurityio/boostsec-rules-management/pull/73

BST-10149: new dependancy with malware rule for sbom-sca

---

scanners/boostsecurityio/supply-chain-inventory/module.yaml

This version of the scanner report the package names with the subpath included so that two package from the same repository doesn't show as the same.

BST-10456: update supply-chain inventory scanner version

---

scanners/boostsecurityio/codeql/module.yaml

Was tested on boost sandbox, with branch https://github.com/boost-sandbox/module-tests-codeql/tree/test-new-codeql-version
i.e. with this registry version.

Update CodeQL scanner version to latest

---

scanners/boostsecurityio/semgrep-pro/module.yaml
scanners/boostsecurityio/semgrep/module.yaml

semgrep:
- update semgrep to 1.74.0
semgrep-pro:
- update semgrep to 1.74.0
- remove the need to write the semgrep token to a file during the setup
- extract the image out of the bash script to make updating it easier

update semgrep 1.74.0

---

scanners/boostsecurityio/supply-chain-inventory/module.yaml

- update supply-chain-inventory to detect gitlab components
- disable warnings from the py3.12 update

BST-11002: update supply-chain-inventory

---

scanners/boostsecurityio/trivy-fs/module.yaml
scanners/boostsecurityio/trivy-sbom/module.yaml

updates the trivy scanners for reporting on missing package lock files

BST-10447: update trivy scanners for error reporting

---

scanners/boostsecurityio/trivy-sbom/module.yaml

we update trivy-sbom to always run scanners as this is
the trivy code path that does language detections
otherwise an error is throw indicating no scanners are running

update trivy-sbom to run scanners

---

scanners/boostsecurityio/boost-sca/rules.yaml

Since this scanner is a combination of the sbom-sca & license scanner, its rules are now just importing from those scanners, making sure they are in sync.

BST-11165: add license type & rule to boost-sca (#132)

---

scanners/boostsecurityio/osv-scanner/module.yaml

Previously the module was making use of the osv-scanner binary. However, in order for the reachability analysis to work for go, the go compiler needs to be present on the server.  Reachability was therefore not working for gitlab runners, ado, etc.
The module is moved to using a container image with osv-scanner and go, enabling reachability analysis on all pipelines.

[BST-11709] Updates osv-scanner to use image and support reachability.

---

scanners/boostsecurityio/trivy-sbom-image/module.yaml
scanners/boostsecurityio/trivy-sbom/module.yaml

BST-11911: bump version of trivy for trivy sbom and trivy sbom image

---

scanners/boostsecurityio/gitleaks/module.yaml

the critical service flag is added to the sarif taxonomy and indicates  whether a secret is from known type

[BST-11946] Adds critical service flag to gitleaks module

---

scanners/boostsecurityio/modelscan/rules.yaml

Adding a label ai-model-with-malicious-behavious to the modelscan rule to enable creating policies
NOTE: the rules management migration to add the new category needs to be merged first.

[BST-12221] Adds AI label to modelscan

---

scanners/boostsecurityio/boost-sca/module.yaml

Brings the trivy version to the same version as for SBOM

[BST-12247] Update trivy version from 0.51 to 0.54.1

---

scanners/boostsecurityio/gitleaks-full/module.yaml
scanners/boostsecurityio/gitleaks/module.yaml

The secret type reported by the previous version of the gitleaks-convertor was based on the Gitleaks rule name, which are a long description of the secret found, not a short secret type.
This also adds the keyscope post-processor to the gitleaks-full scanner.

BST-12156: fix Gitleaks reported secret type

---

scanners/boostsecurityio/gitleaks-full/module.yaml
scanners/boostsecurityio/gitleaks/module.yaml

Reverts boostsecurityio/dev-registry#165
This version of the keyscope convertor would scan the secrets' validity by default, which we only want to do when it is possible to disabled it via ZTP in the frontend in the future.

Revert "BST-12156: revert gitleaks secret-type conversion"

---

scanners/boostsecurityio/gitleaks-full/module.yaml
scanners/boostsecurityio/gitleaks/module.yaml

Both gitleaks & gitleaks-full didn't have the right image for the two post-processor (convertor & keyscope).

BST-12156: fix gitleaks post-processors image versions

---

scanners/boostsecurityio/gitleaks-full/module.yaml
scanners/boostsecurityio/gitleaks/module.yaml

This updaste gitleaks post-processor (keyscope) to strip the secret snippets in order to avoid any change to current finding id (boost-id).
For the gitleaks-full scanner, the snippets are still let trough to comply with legacy behavior.
> [!NOTE]
> The CLI was already stripping those value, but because it was done in previous version of gitleaks convertor, this needs to be replicated.

BST-12156: strip secret snippet in keyscope post-processor

---

scanners/boostsecurityio/gitleaks-full/module.yaml
scanners/boostsecurityio/gitleaks/module.yaml

The env var to enabled/disabled if gitleaks scanner should validate secrets has been renamed to match with the other gitleaks vars.

BST-12323: rename gitleaks validate secret env var

---

scanners/boostsecurityio/gitleaks-full/module.yaml
scanners/boostsecurityio/gitleaks/module.yaml

This update the keyscope post-processor version to enable validation the secrets by default.

BST-12323: reenable validating secrets by default in gitleaks

---

scanners/boostsecurityio/trivy-fs/module.yaml
scanners/boostsecurityio/trivy-image/module.yaml
scanners/boostsecurityio/trivy-sbom-image/module.yaml
scanners/boostsecurityio/trivy-sbom/module.yaml

trivy has started experiencing a number of rate limits when pulling the vulnerability database
to mitigate this issue, they have implemented a repo cache in ECR as well as added support for
pulling from multiple vulnerability databases.

upgrade trivy client and add additional repository urls

---

scanners/boostsecurityio/brakeman/module.yaml
scanners/boostsecurityio/bundler-audit/module.yaml
scanners/boostsecurityio/checkov-tf-plan/module.yaml
scanners/boostsecurityio/checkov/module.yaml
scanners/boostsecurityio/codeql/module.yaml
scanners/boostsecurityio/gitleaks-full/module.yaml
scanners/boostsecurityio/gitleaks/module.yaml
scanners/boostsecurityio/gosec/module.yaml
scanners/boostsecurityio/modelscan/module.yaml
scanners/boostsecurityio/nancy/module.yaml
scanners/boostsecurityio/npm-audit/module.yaml
scanners/boostsecurityio/osv-scanner/module.yaml
scanners/boostsecurityio/safety/module.yaml
scanners/boostsecurityio/semgrep-pro/module.yaml
scanners/boostsecurityio/semgrep/module.yaml
scanners/boostsecurityio/snyk-test/module.yaml
scanners/boostsecurityio/trivy-fs/module.yaml
scanners/boostsecurityio/trivy-image/module.yaml
scanners/boostsecurityio/trivy-sbom-image/module.yaml
scanners/boostsecurityio/trivy-sbom/module.yaml
server-side-scanners/boostsecurityio/blackduck/module.yaml
server-side-scanners/boostsecurityio/sonarqube/module.yaml

For 3rd party scanners, we're to remove the prefix BoostSecurity, recommended to avoid issues with the 3rd parties.

[BST-13457] Removes prefix BoostSecurity for 3rd party scanners.

---

scanners/boostsecurityio/baseline/module.yaml
scanners/boostsecurityio/composition/module.yaml
scanners/boostsecurityio/supply-chain-inventory/module.yaml

This brings the extra resilience to invalid files from the semgrep scanner.

BST-13818 Update composition/sci scanner to latest

---

rules-realm/boostsecurityio/mitre-cwe/rules.yaml

CWE-200 is pretty broad and SARIF scanners reporting on CWE would get the category / label / tag `stored-secrets` which collides with Gitleaks. 
Some semgrep rules have CWE-200 (for instance public S3 bucket on terraform stuff) and it's clearly not a "stored secrets" like Gitleaks would find - so default policies don't jive well with that.
We decided to drop the tag to avoid confusion

BST-14070 - Remove stored-secrets tag on CWE-200

---

scanners/boostsecurityio/brakeman/module.yaml

```
docker buildx imagetools inspect presidentbeef/brakeman:v7.0.0 --format {{.Name}}@{{.Manifest.Digest}}
```
```
presidentbeef/brakeman:v7.0.0@sha256:e16d4d0a8a8b5ee2c5f5f7e25b3d25b81573aa49c973d1e39276848dffe9836d
```
Smoke tested:
https://github.com/boost-sandbox/module-tests-brakeman/actions/runs/13290207203/job/37108839714#step:3:14

Update Brakeman to v7.0.0

---

server-side-scanners/boostsecurityio/cicd/rules.yaml

this pr adds a new rule for security events when webhooks are detected to be missing/disabled

BST-15235: add cicd webhook misconfiguration rule

---

scanners/boostsecurityio/trivy-fs/module.yaml
scanners/boostsecurityio/trivy-image/module.yaml
scanners/boostsecurityio/trivy-sbom-image/module.yaml
scanners/boostsecurityio/trivy-sbom/module.yaml

Smoke tests: https://github.com/boost-sandbox/module-tests-trivy/actions/runs/14516569664

Updated trivy version to 0.61.0

---

scanners/boostsecurityio/npm-audit/module.yaml

The sarif now reports the invocation error to the BE instead of failing with a json error in the pipeline.
Fix stdout issues by updating node version, in previous versions of node the json is not being outputted to stdout making it impossible to parse the error.

Adds error handling for missing lockfiles

---

server-side-scanners/boostsecurityio/sbom-sca/rules.yaml

it was added in a migration to rules db but not here

BST-15555: add 'end-of-life-not-maintained' to categories

---

scanners/boostsecurityio/semgrep/module.yaml
scanners/boostsecurityio/semgrep/prescan_checks.sh

**Improve pre-scan checks:**
Modified the pre-scan check to ensure that custom rules are well-defined:
- Move the check from the module _setup_ to _pre scan step_ so the error details could be visible in boost interface
- Added the following checks:
- A file of a remote URL must be either a ``.yaml`` or ``.yml``
- Fetching the URL must returns a HTTP 200 OK code
- Ensure that the local files or directories exists in the code repository.
- Ensure that the ``.semgrep`` directoy includes at least one yaml file.
**Ease of extending rules:**
- Boost Semgrep rules set can now be referenced by ``boost/sast/rules/semgrep@stable`` or ``boost/sast/rules/semgrep@canary`` instead of providing an URL.
- Local rules support a top level wildcard.
**Smoke tests:**
Smoke tests definition was updated to …

Semgrep - Improve pre scan checks and ease of extending rules

---

scanners/boostsecurityio/baseline/module.yaml

**Description:**
In some cases, the detection of binary files in code repository wasn't working properly due to the boostignore configuration. This PR fix the issue by forcing the inclusion of the detected binary file in the native scanner.
**Smoke tests:**
- https://github.com/boost-sandbox/module-tests-native/actions/runs/16445802130

Fix binary detection
